apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: import-tests-go-wbudwtij-import
  janus-idp.io/tekton: import-tests-go-wbudwtij-import
  backstage.io/kubernetes-id: import-tests-go-wbudwtij-import
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: import-tests-go-wbudwtij-import
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
